import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:firebase_auth/firebase_auth.dart';

import '../providers/theme_provider.dart';
import '../services/database_service.dart';
import '../utils/philippine_time.dart';

class RecentCasesScreen extends StatefulWidget {
  final List<Map<String, dynamic>> recentCases;
  final VoidCallback onCaseUpdated;

  const RecentCasesScreen({
    super.key,
    required this.recentCases,
    required this.onCaseUpdated,
  });

  @override
  State<RecentCasesScreen> createState() => _RecentCasesScreenState();
}

class _RecentCasesScreenState extends State<RecentCasesScreen> {
  final DatabaseService _databaseService = DatabaseService();
  List<Map<String, dynamic>> _recentCases = [];
  bool _isLoading = false;
  String _selectedCategory = 'All';

  // Cache for expanded conversation details
  Map<String, List<Map<String, dynamic>>> _conversationCache = {};
  Set<String> _expandedSessions = {};

  @override
  void initState() {
    super.initState();
    _recentCases = List.from(widget.recentCases);
    _debugPrintCategories();
  }

  void _debugPrintCategories() {
    final categories = _recentCases
        .map((chatCase) => _getCategoryFromCase(chatCase))
        .toSet()
        .toList();
    print('Actual categories in recent cases: $categories');
  }

  // Helper method to get category from either data format
  String _getCategoryFromCase(Map<String, dynamic> chatCase) {
    if (chatCase.containsKey('category')) {
      return chatCase['category']?.toString() ?? 'General';
    } else if (chatCase.containsKey('categories')) {
      final categories = chatCase['categories'] as List<dynamic>?;
      return categories?.isNotEmpty == true ? categories!.first.toString() : 'General';
    }
    return 'General';
  }

  // Check if this is session data
  bool _isSessionData(Map<String, dynamic> chatCase) {
    return chatCase.containsKey('first_question') &&
        chatCase.containsKey('session_id') &&
        chatCase['session_id'] != null;
  }

  // Get session ID for session data
  String? _getSessionId(Map<String, dynamic> chatCase) {
    if (_isSessionData(chatCase)) {
      return chatCase['session_id']?.toString();
    }
    return null;
  }

  // Fetch conversation details for a session
  Future<List<Map<String, dynamic>>> _fetchConversationDetails(String sessionId) async {
    if (_conversationCache.containsKey(sessionId)) {
      return _conversationCache[sessionId]!;
    }

    try {
      final messages = await _databaseService.getSessionMessages(sessionId);
      messages.sort((a, b) {
        final aTime = a['created_at']?.toString();
        final bTime = b['created_at']?.toString();
        if (aTime == null || bTime == null) return 0;
        try {
          return DateTime.parse(aTime).compareTo(DateTime.parse(bTime));
        } catch (e) {
          return 0;
        }
      });

      _conversationCache[sessionId] = messages;
      return messages;
    } catch (e) {
      print('Error fetching conversation details for session $sessionId: $e');
      return [];
    }
  }

  // NEW: Share individual Q&A pair
  Future<void> _shareQAPair(String question, String answer, String category, String createdAt) async {
    try {
      final shareText = '''
📋 Legal Q&A from LawBot

❓ Question:
$question

🤖 LawBot Answer:
$answer

📂 Category: $category
⏰ ${createdAt.isNotEmpty ? PhilippineTime.formatChatHistoryTime(createdAt) : 'Unknown date'}

---
Generated by LawBot - Your AI Legal Assistant for Philippine Cybercrime Laws
      ''';

      await Share.share(
        shareText.trim(),
        subject: 'Legal Q&A from LawBot',
      );
    } catch (e) {
      print('Error sharing Q&A: $e');
      _showSnackBar('Failed to share Q&A. Please try again.', Colors.red);
    }
  }

  // NEW: Save individual Q&A pair
  Future<void> _saveQAPair(String question, String answer, String category, List<String>? keywords) async {
    if (FirebaseAuth.instance.currentUser == null) {
      _showSignInRequiredDialog();
      return;
    }

    try {
      // Check if already saved
      final isAlreadySaved = await _databaseService.isAdviceSaved(question, answer);

      if (isAlreadySaved) {
        _showSnackBar('This Q&A is already saved!', Colors.orange);
        return;
      }

      await _databaseService.saveAdvice(
        question: question,
        answer: answer,
        category: category,
        tags: keywords,
      );

      _showSnackBar('Q&A saved to your bookmarks!', Colors.green);
    } catch (e) {
      print('Error saving Q&A: $e');
      _showSnackBar('Failed to save Q&A. Please try again.', Colors.red);
    }
  }

  void _showSignInRequiredDialog() {
    final isDark = context.read<ThemeProvider>().isDarkMode;

    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: isDark ? const Color(0xFF1E293B) : Colors.white,
        title: Row(
          children: [
            Icon(
              Icons.account_circle_outlined,
              color: isDark ? const Color(0xFF60A5FA) : const Color(0xFF2563EB),
            ),
            const SizedBox(width: 8),
            Text(
              'Sign In Required',
              style: TextStyle(
                color: isDark ? Colors.white : Colors.black,
              ),
            ),
          ],
        ),
        content: Text(
          'You need to sign in to save Q&A pairs to your bookmarks.',
          style: TextStyle(
            color: isDark ? Colors.grey[300] : Colors.grey[700],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: Text(
              'Maybe Later',
              style: TextStyle(
                color: isDark ? Colors.grey[400] : Colors.grey[600],
              ),
            ),
          ),
          ElevatedButton(
            onPressed: () {
              Navigator.pop(context);
              Navigator.pushNamed(context, '/signin');
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: isDark ? const Color(0xFF3B82F6) : const Color(0xFF2563EB),
            ),
            child: const Text(
              'Sign In',
              style: TextStyle(color: Colors.white),
            ),
          ),
        ],
      ),
    );
  }

  // Dynamic categories getter
  List<String> get categories {
    final Set<String> uniqueCategories = {'All'};
    final expectedCategories = [
      'Cybercrime Prevention Act',
      'Online Harassment',
      'E-commerce Fraud',
      'Identity Theft',
      'Data Privacy',
      'Unauthorized Access',
      'General'
    ];

    for (var chatCase in _recentCases) {
      final category = _getCategoryFromCase(chatCase);
      if (expectedCategories.contains(category)) {
        uniqueCategories.add(category);
      }
    }

    List<String> orderedCategories = ['All'];
    for (String expected in expectedCategories) {
      if (uniqueCategories.contains(expected)) {
        orderedCategories.add(expected);
      }
    }

    return orderedCategories;
  }

  Future<void> _refreshRecentCases() async {
    setState(() {
      _isLoading = true;
    });

    try {
      final updatedCases = await _databaseService.getChatHistory(limit: 50);
      setState(() {
        _recentCases = updatedCases;
        _isLoading = false;
        _conversationCache.clear();
        _expandedSessions.clear();
      });
      widget.onCaseUpdated();
    } catch (e) {
      print('Error refreshing recent cases: $e');
      setState(() {
        _isLoading = false;
      });
      _showSnackBar('Failed to refresh recent cases. Please try again.', Colors.red);
    }
  }

  void _showSnackBar(String message, Color color) {
    if (!mounted) return;

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: color,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        margin: const EdgeInsets.all(16),
      ),
    );
  }

  List<Map<String, dynamic>> get _filteredCases {
    if (_selectedCategory == 'All') {
      return _recentCases;
    }
    return _recentCases.where((chatCase) {
      final caseCategory = _getCategoryFromCase(chatCase);
      return caseCategory == _selectedCategory;
    }).toList();
  }

  @override
  Widget build(BuildContext context) {
    final themeProvider = context.watch<ThemeProvider>();
    final isDark = themeProvider.isDarkMode;

    return Scaffold(
      backgroundColor: isDark ? const Color(0xFF0F172A) : Colors.grey[50],
      appBar: AppBar(
        backgroundColor: isDark ? const Color(0xFF0F172A) : Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: Icon(
            Icons.arrow_back_rounded,
            color: isDark ? Colors.white : const Color(0xFF2563EB),
          ),
          onPressed: () => Navigator.pop(context),
        ),
        title: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: isDark
                    ? const Color(0xFF3B82F6).withOpacity(0.2)
                    : const Color(0xFF2563EB).withOpacity(0.1),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(
                  color: isDark
                      ? const Color(0xFF3B82F6).withOpacity(0.5)
                      : const Color(0xFF2563EB).withOpacity(0.3),
                  width: 1,
                ),
              ),
              child: Icon(
                Icons.history_rounded,
                color: isDark ? const Color(0xFF60A5FA) : const Color(0xFF2563EB),
                size: 20,
              ),
            ),
            const SizedBox(width: 12),
            Flexible(
              child: Text(
                'Recent Cases',
                style: TextStyle(
                  fontSize: 20,
                  fontWeight: FontWeight.bold,
                  color: isDark ? Colors.white : Colors.black,
                ),
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ],
        ),
        actions: [
          IconButton(
            onPressed: _refreshRecentCases,
            icon: Icon(
              Icons.refresh_rounded,
              color: isDark ? Colors.white : const Color(0xFF2563EB),
            ),
          ),
        ],
      ),
      body: RefreshIndicator(
        onRefresh: _refreshRecentCases,
        child: _isLoading
            ? Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CircularProgressIndicator(
                color: isDark ? const Color(0xFF3B82F6) : const Color(0xFF2563EB),
              ),
              const SizedBox(height: 16),
              Text(
                'Loading recent cases...',
                style: TextStyle(
                  color: isDark ? Colors.white : Colors.black,
                ),
              ),
            ],
          ),
        )
            : Column(
          children: [
            // Category filter chips (unchanged)
            if (categories.length > 1)
              Container(
                width: double.infinity,
                decoration: BoxDecoration(
                  color: isDark ? const Color(0xFF1E293B) : Colors.white,
                  border: Border(
                    bottom: BorderSide(
                      color: isDark ? const Color(0xFF334155) : Colors.grey.shade200,
                      width: 1,
                    ),
                  ),
                ),
                child: Padding(
                  padding: const EdgeInsets.fromLTRB(16, 8, 16, 16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Filter by Category',
                        style: TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.bold,
                          color: isDark ? Colors.white : Colors.black,
                        ),
                      ),
                      const SizedBox(height: 8),
                      Wrap(
                        spacing: 8,
                        runSpacing: 4,
                        children: categories.map((category) {
                          final isSelected = _selectedCategory == category;
                          return ChoiceChip(
                            label: Text(
                              category == 'All' ? 'All Categories' : category,
                              style: TextStyle(
                                fontSize: 12,
                                color: isSelected
                                    ? Colors.white
                                    : isDark
                                    ? Colors.grey[300]
                                    : Colors.grey[700],
                              ),
                            ),
                            selected: isSelected,
                            onSelected: (selected) {
                              if (selected) {
                                setState(() {
                                  _selectedCategory = category;
                                });
                              }
                            },
                            backgroundColor: isDark ? const Color(0xFF334155) : Colors.grey[200],
                            selectedColor: isDark ? const Color(0xFF3B82F6) : const Color(0xFF2563EB),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                              side: BorderSide(
                                color: isSelected
                                    ? (isDark ? const Color(0xFF3B82F6) : const Color(0xFF2563EB))
                                    : (isDark ? const Color(0xFF334155) : Colors.grey[300]!),
                                width: 1,
                              ),
                            ),
                            labelPadding: const EdgeInsets.symmetric(horizontal: 8, vertical: 0),
                            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 0),
                          );
                        }).toList(),
                      ),
                    ],
                  ),
                ),
              ),
            // Cases List
            Expanded(
              child: _filteredCases.isEmpty
                  ? _buildEmptyState(isDark)
                  : RefreshIndicator(
                onRefresh: _refreshRecentCases,
                child: ListView.builder(
                  padding: const EdgeInsets.all(16),
                  itemCount: _filteredCases.length,
                  itemBuilder: (context, index) {
                    final chatCase = _filteredCases[index];
                    return _buildCaseCard(chatCase, isDark);
                  },
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildEmptyState(bool isDark) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              width: 120,
              height: 120,
              decoration: BoxDecoration(
                color: isDark
                    ? const Color(0xFF3B82F6).withOpacity(0.1)
                    : const Color(0xFF2563EB).withOpacity(0.1),
                shape: BoxShape.circle,
                border: Border.all(
                  color: isDark
                      ? const Color(0xFF3B82F6).withOpacity(0.3)
                      : const Color(0xFF2563EB).withOpacity(0.3),
                  width: 2,
                ),
              ),
              child: Icon(
                Icons.chat_bubble_outline,
                size: 60,
                color: isDark ? const Color(0xFF60A5FA) : const Color(0xFF2563EB),
              ),
            ),
            const SizedBox(height: 24),
            Text(
              _selectedCategory == 'All'
                  ? 'No Cases Yet'
                  : 'No $_selectedCategory Cases Found',
              style: TextStyle(
                fontSize: 24,
                fontWeight: FontWeight.bold,
                color: isDark ? Colors.white : Colors.black,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 12),
            Text(
              _selectedCategory == 'All'
                  ? 'Start asking legal questions in the chat to see your conversation history here.'
                  : 'No cases found matching "$_selectedCategory". Try asking questions about this topic or select "All" to see all cases.',
              style: TextStyle(
                fontSize: 16,
                color: isDark ? Colors.grey[400] : Colors.grey[600],
                height: 1.5,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 32),
            ElevatedButton.icon(
              onPressed: () => Navigator.pop(context),
              style: ElevatedButton.styleFrom(
                backgroundColor: isDark ? const Color(0xFF3B82F6) : const Color(0xFF2563EB),
                padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
              icon: const Icon(Icons.chat, color: Colors.white),
              label: const Text(
                'Start Chatting',
                style: TextStyle(
                  color: Colors.white,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildCaseCard(Map<String, dynamic> chatCase, bool isDark) {
    final sessionId = _getSessionId(chatCase);
    final isSessionData = _isSessionData(chatCase);
    final isExpanded = sessionId != null && _expandedSessions.contains(sessionId);

    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Container(
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(16),
          color: isDark ? const Color(0xFF1E293B) : Colors.white,
          border: Border.all(
            color: isDark ? const Color(0xFF374151) : const Color(0xFFE5E7EB),
            width: 1,
          ),
          boxShadow: [
            BoxShadow(
              color: isDark
                  ? Colors.black.withOpacity(0.2)
                  : Colors.grey.withOpacity(0.1),
              blurRadius: 8,
              offset: const Offset(0, 2),
            ),
          ],
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildCaseHeader(chatCase, isDark),
            const SizedBox(height: 16),

            if (isSessionData && sessionId != null) ...[
              _buildSessionContent(chatCase, sessionId, isDark),
            ] else ...[
              _buildIndividualMessageContent(chatCase, isDark),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildCaseHeader(Map<String, dynamic> chatCase, bool isDark) {
    String category;
    String createdAt;
    double? confidenceScore;

    if (chatCase.containsKey('question')) {
      category = chatCase['category'] ?? 'General';
      createdAt = chatCase['created_at'] ?? '';
      confidenceScore = chatCase['confidence_score'] as double?;
    } else {
      final categories = chatCase['categories'] as List<dynamic>?;
      category = categories?.isNotEmpty == true ? categories!.first.toString() : 'General';
      createdAt = chatCase['first_created_at'] ?? chatCase['last_created_at'] ?? '';
      confidenceScore = chatCase['avg_confidence'] as double?;
    }

    return Row(
      children: [
        Flexible(
          flex: 2,
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: isDark
                    ? [const Color(0xFF3B82F6), const Color(0xFF1D4ED8)]
                    : [const Color(0xFF2563EB), const Color(0xFF1D4ED8)],
              ),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Text(
              category,
              style: const TextStyle(
                fontSize: 12,
                color: Colors.white,
                fontWeight: FontWeight.w600,
              ),
              overflow: TextOverflow.ellipsis,
              maxLines: 1,
            ),
          ),
        ),
        const SizedBox(width: 8),
        Flexible(
          flex: 3,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              if (confidenceScore != null) ...[
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 4),
                  decoration: BoxDecoration(
                    color: confidenceScore > 0.8
                        ? Colors.green.withOpacity(0.1)
                        : confidenceScore > 0.6
                        ? Colors.orange.withOpacity(0.1)
                        : Colors.grey.withOpacity(0.1),
                    borderRadius: BorderRadius.circular(8),
                    border: Border.all(
                      color: confidenceScore > 0.8
                          ? Colors.green
                          : confidenceScore > 0.6
                          ? Colors.orange
                          : Colors.grey,
                      width: 1,
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(
                        Icons.verified_rounded,
                        size: 10,
                        color: confidenceScore > 0.8
                            ? Colors.green
                            : confidenceScore > 0.6
                            ? Colors.orange
                            : Colors.grey,
                      ),
                      const SizedBox(width: 2),
                      Text(
                        '${(confidenceScore * 100).round()}%',
                        style: TextStyle(
                          fontSize: 9,
                          color: confidenceScore > 0.8
                              ? Colors.green
                              : confidenceScore > 0.6
                              ? Colors.orange
                              : Colors.grey,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(width: 6),
              ],
              Flexible(
                child: Text(
                  createdAt.isNotEmpty
                      ? PhilippineTime.formatChatHistoryTime(createdAt)
                      : 'Unknown date',
                  style: TextStyle(
                    fontSize: 11,
                    color: isDark ? Colors.grey[400] : Colors.grey[500],
                  ),
                  overflow: TextOverflow.ellipsis,
                  maxLines: 1,
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildSessionContent(Map<String, dynamic> chatCase, String sessionId, bool isDark) {
    final isExpanded = _expandedSessions.contains(sessionId);
    final firstQuestion = chatCase['first_question'] as String? ?? 'No question';
    final messageCount = chatCase['message_count'] as int? ?? 0;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          width: double.infinity,
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: isDark
                ? const Color(0xFF3B82F6).withOpacity(0.1)
                : const Color(0xFF2563EB).withOpacity(0.05),
            borderRadius: BorderRadius.circular(12),
            border: Border.all(
              color: isDark
                  ? const Color(0xFF3B82F6).withOpacity(0.3)
                  : const Color(0xFF2563EB).withOpacity(0.2),
              width: 1,
            ),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Icon(
                    Icons.help_outline,
                    size: 16,
                    color: isDark ? const Color(0xFF60A5FA) : const Color(0xFF2563EB),
                  ),
                  const SizedBox(width: 6),
                  Text(
                    'First Question',
                    style: TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.w600,
                      color: isDark ? const Color(0xFF60A5FA) : const Color(0xFF2563EB),
                    ),
                  ),
                  const Spacer(),
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                    decoration: BoxDecoration(
                      color: isDark ? Colors.blue[900]?.withOpacity(0.5) : Colors.blue[50],
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Text(
                      '$messageCount messages',
                      style: TextStyle(
                        fontSize: 10,
                        color: isDark ? Colors.blue[300] : Colors.blue[700],
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 8),
              Text(
                firstQuestion,
                style: TextStyle(
                  fontSize: 14,
                  color: isDark ? Colors.white : Colors.black,
                  height: 1.4,
                ),
                softWrap: true,
              ),
            ],
          ),
        ),

        const SizedBox(height: 12),

        InkWell(
          onTap: () async {
            if (isExpanded) {
              setState(() {
                _expandedSessions.remove(sessionId);
              });
            } else {
              setState(() {
                _expandedSessions.add(sessionId);
              });
              if (!_conversationCache.containsKey(sessionId)) {
                await _fetchConversationDetails(sessionId);
                if (mounted) setState(() {});
              }
            }
          },
          borderRadius: BorderRadius.circular(8),
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
            decoration: BoxDecoration(
              color: isDark
                  ? const Color(0xFF10B981).withOpacity(0.1)
                  : const Color(0xFF10B981).withOpacity(0.05),
              borderRadius: BorderRadius.circular(8),
              border: Border.all(
                color: isDark
                    ? const Color(0xFF10B981).withOpacity(0.3)
                    : const Color(0xFF10B981).withOpacity(0.2),
                width: 1,
              ),
            ),
            child: Row(
              children: [
                const Icon(
                  Icons.smart_toy_outlined,
                  size: 16,
                  color: Color(0xFF10B981),
                ),
                const SizedBox(width: 6),
                Text(
                  isExpanded ? 'Hide Full Conversation' : 'Show Full Conversation',
                  style: const TextStyle(
                    fontSize: 12,
                    fontWeight: FontWeight.w600,
                    color: Color(0xFF10B981),
                  ),
                ),
                const Spacer(),
                Icon(
                  isExpanded ? Icons.expand_less : Icons.expand_more,
                  size: 16,
                  color: const Color(0xFF10B981),
                ),
              ],
            ),
          ),
        ),

        if (isExpanded) ...[
          const SizedBox(height: 16),
          _buildFullConversation(sessionId, isDark),
        ],
      ],
    );
  }

  Widget _buildFullConversation(String sessionId, bool isDark) {
    final messages = _conversationCache[sessionId];

    if (messages == null) {
      return Container(
        padding: const EdgeInsets.all(16),
        child: Row(
          children: [
            SizedBox(
              width: 16,
              height: 16,
              child: CircularProgressIndicator(
                strokeWidth: 2,
                color: isDark ? const Color(0xFF3B82F6) : const Color(0xFF2563EB),
              ),
            ),
            const SizedBox(width: 12),
            Text(
              'Loading conversation...',
              style: TextStyle(
                color: isDark ? Colors.grey[400] : Colors.grey[600],
              ),
            ),
          ],
        ),
      );
    }

    if (messages.isEmpty) {
      return Container(
        padding: const EdgeInsets.all(16),
        child: Text(
          'No messages found in this conversation.',
          style: TextStyle(
            color: isDark ? Colors.grey[400] : Colors.grey[600],
          ),
        ),
      );
    }

    return Column(
      children: messages.map((message) => _buildConversationMessage(message, isDark)).toList(),
    );
  }

  // UPDATED: Individual conversation message with share/save buttons
  Widget _buildConversationMessage(Map<String, dynamic> message, bool isDark) {
    final question = message['question'] ?? 'No question';
    final answer = message['answer'] ?? 'No answer';
    final createdAt = message['created_at'] ?? '';
    final category = message['category'] ?? 'General';
    final metadata = message['metadata'] as Map<String, dynamic>?;
    final keywords = metadata?['keywords'] as List<dynamic>?;
    final recommendations = metadata?['recommendations'] as List<dynamic>?;

    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      child: Column(
        children: [
          // Question
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: isDark
                  ? const Color(0xFF3B82F6).withOpacity(0.1)
                  : const Color(0xFF2563EB).withOpacity(0.05),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: isDark
                    ? const Color(0xFF3B82F6).withOpacity(0.3)
                    : const Color(0xFF2563EB).withOpacity(0.2),
                width: 1,
              ),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Icon(
                      Icons.help_outline,
                      size: 14,
                      color: isDark ? const Color(0xFF60A5FA) : const Color(0xFF2563EB),
                    ),
                    const SizedBox(width: 6),
                    Text(
                      'Q:',
                      style: TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.w600,
                        color: isDark ? const Color(0xFF60A5FA) : const Color(0xFF2563EB),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 6),
                Text(
                  question,
                  style: TextStyle(
                    fontSize: 13,
                    color: isDark ? Colors.white : Colors.black,
                    height: 1.4,
                  ),
                ),
              ],
            ),
          ),

          const SizedBox(height: 8),

          // Answer with NEW action buttons
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: isDark
                  ? const Color(0xFF10B981).withOpacity(0.1)
                  : const Color(0xFF10B981).withOpacity(0.05),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: isDark
                    ? const Color(0xFF10B981).withOpacity(0.3)
                    : const Color(0xFF10B981).withOpacity(0.2),
                width: 1,
              ),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    const Icon(
                      Icons.smart_toy_outlined,
                      size: 14,
                      color: Color(0xFF10B981),
                    ),
                    const SizedBox(width: 6),
                    const Text(
                      'A:',
                      style: TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.w600,
                        color: Color(0xFF10B981),
                      ),
                    ),
                    const Spacer(),
                    Text(
                      PhilippineTime.formatChatHistoryTime(createdAt),
                      style: TextStyle(
                        fontSize: 10,
                        color: isDark ? Colors.grey[400] : Colors.grey[500],
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 6),
                Text(
                  answer,
                  style: TextStyle(
                    fontSize: 13,
                    color: isDark ? Colors.white : Colors.black,
                    height: 1.4,
                  ),
                ),

                // Keywords Section
                if (keywords != null && keywords.isNotEmpty) ...[
                  const SizedBox(height: 12),
                  Wrap(
                    spacing: 4,
                    runSpacing: 4,
                    children: keywords.take(5).map((keyword) => Container(
                      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                      decoration: BoxDecoration(
                        color: (isDark ? Colors.blue[900] : Colors.blue[50])?.withOpacity(0.7),
                        borderRadius: BorderRadius.circular(8),
                        border: Border.all(
                          color: (isDark ? Colors.blue[700] : Colors.blue[200])!,
                          width: 0.5,
                        ),
                      ),
                      child: Text(
                        keyword.toString(),
                        style: TextStyle(
                          fontSize: 10,
                          color: isDark ? Colors.blue[300] : Colors.blue[700],
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                    )).toList(),
                  ),
                ],

                // Recommendations Section
                if (recommendations != null && recommendations.isNotEmpty) ...[
                  const SizedBox(height: 12),
                  Container(
                    padding: const EdgeInsets.all(8),
                    decoration: BoxDecoration(
                      color: isDark
                          ? const Color(0xFFD97706).withOpacity(0.1)
                          : const Color(0xFFF59E0B).withOpacity(0.05),
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(
                        color: isDark
                            ? const Color(0xFFD97706).withOpacity(0.3)
                            : const Color(0xFFF59E0B).withOpacity(0.2),
                        width: 1,
                      ),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            Icon(
                              Icons.lightbulb_outline,
                              size: 12,
                              color: isDark ? Colors.amber[300] : Colors.amber[700],
                            ),
                            const SizedBox(width: 4),
                            Text(
                              'Recommendations:',
                              style: TextStyle(
                                fontSize: 11,
                                fontWeight: FontWeight.w600,
                                color: isDark ? Colors.amber[300] : Colors.amber[700],
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 6),
                        ...recommendations.take(3).map((rec) => Padding(
                          padding: const EdgeInsets.only(bottom: 3),
                          child: Row(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Container(
                                width: 3,
                                height: 3,
                                margin: const EdgeInsets.only(top: 5),
                                decoration: BoxDecoration(
                                  color: isDark ? Colors.amber[300] : Colors.amber[700],
                                  shape: BoxShape.circle,
                                ),
                              ),
                              const SizedBox(width: 6),
                              Expanded(
                                child: Text(
                                  rec.toString(),
                                  style: TextStyle(
                                    fontSize: 11,
                                    color: isDark ? Colors.white : Colors.black,
                                    height: 1.3,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        )),
                      ],
                    ),
                  ),
                ],

                // NEW: Action buttons for each Q&A pair
                const SizedBox(height: 12),
                Row(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    // Save button
                    InkWell(
                      onTap: () => _saveQAPair(
                        question,
                        answer,
                        category,
                        keywords?.cast<String>(),
                      ),
                      borderRadius: BorderRadius.circular(8),
                      child: Container(
                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                        decoration: BoxDecoration(
                          color: Colors.amber.withOpacity(0.1),
                          borderRadius: BorderRadius.circular(8),
                          border: Border.all(
                            color: Colors.amber.withOpacity(0.3),
                            width: 1,
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Icon(
                              Icons.bookmark_border,
                              size: 14,
                              color: Colors.amber[700],
                            ),
                            const SizedBox(width: 4),
                            Text(
                              'Save',
                              style: TextStyle(
                                fontSize: 11,
                                color: Colors.amber[700],
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(width: 8),
                    // Share button
                    InkWell(
                      onTap: () => _shareQAPair(question, answer, category, createdAt),
                      borderRadius: BorderRadius.circular(8),
                      child: Container(
                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                        decoration: BoxDecoration(
                          color: Colors.blue.withOpacity(0.1),
                          borderRadius: BorderRadius.circular(8),
                          border: Border.all(
                            color: Colors.blue.withOpacity(0.3),
                            width: 1,
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Icon(
                              Icons.share_outlined,
                              size: 14,
                              color: Colors.blue[700],
                            ),
                            const SizedBox(width: 4),
                            Text(
                              'Share',
                              style: TextStyle(
                                fontSize: 11,
                                color: Colors.blue[700],
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // UPDATED: Individual message content with share/save buttons
  Widget _buildIndividualMessageContent(Map<String, dynamic> chatCase, bool isDark) {
    final question = chatCase['question'] ?? 'No question';
    final answer = chatCase['answer'] ?? 'No answer';
    final category = chatCase['category'] ?? 'General';
    final createdAt = chatCase['created_at'] ?? '';
    final metadata = chatCase['metadata'] as Map<String, dynamic>?;
    final keywords = metadata?['keywords'] as List<dynamic>?;
    final recommendations = metadata?['recommendations'] as List<dynamic>?;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Question
        Container(
          width: double.infinity,
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: isDark
                ? const Color(0xFF3B82F6).withOpacity(0.1)
                : const Color(0xFF2563EB).withOpacity(0.05),
            borderRadius: BorderRadius.circular(12),
            border: Border.all(
              color: isDark
                  ? const Color(0xFF3B82F6).withOpacity(0.3)
                  : const Color(0xFF2563EB).withOpacity(0.2),
              width: 1,
            ),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Icon(
                    Icons.help_outline,
                    size: 16,
                    color: isDark ? const Color(0xFF60A5FA) : const Color(0xFF2563EB),
                  ),
                  const SizedBox(width: 6),
                  Text(
                    'Question',
                    style: TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.w600,
                      color: isDark ? const Color(0xFF60A5FA) : const Color(0xFF2563EB),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 8),
              Text(
                question,
                style: TextStyle(
                  fontSize: 14,
                  color: isDark ? Colors.white : Colors.black,
                  height: 1.4,
                ),
                softWrap: true,
              ),
            ],
          ),
        ),
        const SizedBox(height: 12),

        // Answer with NEW action buttons
        Container(
          width: double.infinity,
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: isDark
                ? const Color(0xFF10B981).withOpacity(0.1)
                : const Color(0xFF10B981).withOpacity(0.05),
            borderRadius: BorderRadius.circular(12),
            border: Border.all(
              color: isDark
                  ? const Color(0xFF10B981).withOpacity(0.3)
                  : const Color(0xFF10B981).withOpacity(0.2),
              width: 1,
            ),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  const Icon(
                    Icons.smart_toy_outlined,
                    size: 16,
                    color: Color(0xFF10B981),
                  ),
                  const SizedBox(width: 6),
                  const Text(
                    'LawBot Answer',
                    style: TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.w600,
                      color: Color(0xFF10B981),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 8),
              Text(
                answer,
                style: TextStyle(
                  fontSize: 14,
                  color: isDark ? Colors.white : Colors.black,
                  height: 1.4,
                ),
                softWrap: true,
              ),

              // Keywords and recommendations sections (same as before)
              if (keywords != null && keywords.isNotEmpty) ...[
                const SizedBox(height: 16),
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: isDark
                        ? const Color(0xFF1E40AF).withOpacity(0.1)
                        : const Color(0xFF3B82F6).withOpacity(0.05),
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: isDark
                          ? const Color(0xFF1E40AF).withOpacity(0.3)
                          : const Color(0xFF3B82F6).withOpacity(0.2),
                      width: 1,
                    ),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          Icon(
                            Icons.label_outline,
                            size: 16,
                            color: isDark ? Colors.blue[300] : Colors.blue[700],
                          ),
                          const SizedBox(width: 6),
                          Text(
                            'Legal Keywords',
                            style: TextStyle(
                              fontSize: 12,
                              fontWeight: FontWeight.w600,
                              color: isDark ? Colors.blue[300] : Colors.blue[700],
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 8),
                      LayoutBuilder(
                        builder: (context, constraints) {
                          return Wrap(
                            spacing: 6,
                            runSpacing: 6,
                            children: keywords.map((keyword) => Container(
                              constraints: BoxConstraints(
                                maxWidth: constraints.maxWidth * 0.45,
                              ),
                              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                              decoration: BoxDecoration(
                                color: (isDark ? Colors.blue[900] : Colors.blue[50])?.withOpacity(0.7),
                                borderRadius: BorderRadius.circular(12),
                                border: Border.all(
                                  color: (isDark ? Colors.blue[700] : Colors.blue[200])!,
                                  width: 1,
                                ),
                              ),
                              child: Text(
                                keyword.toString(),
                                style: TextStyle(
                                  fontSize: 10,
                                  color: isDark ? Colors.blue[300] : Colors.blue[700],
                                  fontWeight: FontWeight.w500,
                                ),
                                overflow: TextOverflow.ellipsis,
                                maxLines: 1,
                              ),
                            )).toList(),
                          );
                        },
                      ),
                    ],
                  ),
                ),
              ],

              if (recommendations != null && recommendations.isNotEmpty) ...[
                const SizedBox(height: 16),
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: isDark
                        ? const Color(0xFFD97706).withOpacity(0.1)
                        : const Color(0xFFF59E0B).withOpacity(0.05),
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: isDark
                          ? const Color(0xFFD97706).withOpacity(0.3)
                          : const Color(0xFFF59E0B).withOpacity(0.2),
                      width: 1,
                    ),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          Icon(
                            Icons.lightbulb_outline,
                            size: 16,
                            color: isDark ? Colors.amber[300] : Colors.amber[700],
                          ),
                          const SizedBox(width: 6),
                          Text(
                            'AI Recommendations',
                            style: TextStyle(
                              fontSize: 12,
                              fontWeight: FontWeight.w600,
                              color: isDark ? Colors.amber[300] : Colors.amber[700],
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 8),
                      ...recommendations.take(3).map((rec) => Padding(
                        padding: const EdgeInsets.only(bottom: 6),
                        child: Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: 4,
                              height: 4,
                              margin: const EdgeInsets.only(top: 6),
                              decoration: BoxDecoration(
                                color: isDark ? Colors.amber[300] : Colors.amber[700],
                                shape: BoxShape.circle,
                              ),
                            ),
                            const SizedBox(width: 8),
                            Expanded(
                              child: Text(
                                rec.toString(),
                                style: TextStyle(
                                  fontSize: 12,
                                  color: isDark ? Colors.white : Colors.black,
                                  height: 1.4,
                                ),
                                softWrap: true,
                              ),
                            ),
                          ],
                        ),
                      )),
                    ],
                  ),
                ),
              ],

              // NEW: Action buttons for individual Q&A
              const SizedBox(height: 12),
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  // Save button
                  InkWell(
                    onTap: () => _saveQAPair(
                      question,
                      answer,
                      category,
                      keywords?.cast<String>(),
                    ),
                    borderRadius: BorderRadius.circular(8),
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                      decoration: BoxDecoration(
                        color: Colors.amber.withOpacity(0.1),
                        borderRadius: BorderRadius.circular(8),
                        border: Border.all(
                          color: Colors.amber.withOpacity(0.3),
                          width: 1,
                        ),
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Icon(
                            Icons.bookmark_border,
                            size: 14,
                            color: Colors.amber[700],
                          ),
                          const SizedBox(width: 4),
                          Text(
                            'Save',
                            style: TextStyle(
                              fontSize: 11,
                              color: Colors.amber[700],
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(width: 8),
                  // Share button
                  InkWell(
                    onTap: () => _shareQAPair(question, answer, category, createdAt),
                    borderRadius: BorderRadius.circular(8),
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                      decoration: BoxDecoration(
                        color: Colors.blue.withOpacity(0.1),
                        borderRadius: BorderRadius.circular(8),
                        border: Border.all(
                          color: Colors.blue.withOpacity(0.3),
                          width: 1,
                        ),
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Icon(
                            Icons.share_outlined,
                            size: 14,
                            color: Colors.blue[700],
                          ),
                          const SizedBox(width: 4),
                          Text(
                            'Share',
                            style: TextStyle(
                              fontSize: 11,
                              color: Colors.blue[700],
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ],
    );
  }
}